services:
  app-db:
    image: postgres:13
    environment:
      POSTGRES_DB: 3morpion
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

    volumes:
      - ./Db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  tree-db:
    image: postgres:13
    environment:
      POSTGRES_DB: tree
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

    volumes:
      - ./Lecon/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"